[package]
name = "pistreaming-api"
version.workspace = true
edition.workspace = true

[dependencies]
pistreaming-core = { path = "../core" }
pistreaming-store = { path = "../store" }
pistreaming-addons = { path = "../addons" }
pistreaming-torrent = { path = "../torrent" }
pistreaming-media = { path = "../media" }
bytes.workspace = true
http.workspace = true
tokio-util.workspace = true
futures.workspace = true
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
parking_lot.workspace = true

[dev-dependencies]
tower = { workspace = true, features = ["util"] }
http-body-util = "0.1"
tempfile.workspace = true
wiremock.workspace = true
reqwest.workspace = true
